import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  ASSETS_RELATIVE_PATH,
  FALLBACK_PATTERN,
  HOSTING_CONFIG_NAME,
  NOT_FOUND_DOCUMENT,
  ROUTES_RELATIVE_PATH,
  REQUIRED_ARTIFACTS,
  correctRouteTable,
  prepareBundle,
  readRouteTable,
  stageBundle,
  verifyRouteTable,
} from '../../../scripts/edgeone/routes.mjs';

/**
 * Hosting-boundary regression for the EdgeOne deploy bundle.
 *
 * The deployed artifact must answer a real 404 for unknown paths. Without an authored route table the
 * platform serves the application shell with status 200 for every unknown path — including a missing
 * script — so the published `404.html` is never reached.
 *
 * The route table is generated by the pinned EdgeOne CLI (`pages generate-routes`) from the complete
 * bundle layout; `tests/fixtures/edgeone/generated-routes.json` is that CLI's unmodified output for
 * this application, captured from edgeone@1.4.6 running offline against a staged bundle. These tests
 * therefore assert on real provider-tooling output and on what our bounded correction does to it —
 * not on a simulation of the routing model.
 *
 * What stays unprovable here: the status code a *deployed* request receives. The compiled pattern,
 * the embedded configuration and the corrected fallback are the artifact; the provider's runtime
 * behaviour is a release-time measurement.
 */
type Route = {
  src?: string;
  dest?: string;
  status?: number;
  handle?: string;
  'server-name'?: string;
};
type RouteTable = {
  version: number;
  routes: Route[];
  conf?: { headers?: unknown[]; redirects?: unknown[]; rewrites?: unknown[]; caches?: unknown[] };
};

const root = process.cwd();
const publicRoot = path.resolve(root, 'public');
const fixturePath = path.resolve(root, 'tests/fixtures/edgeone/generated-routes.json');
const generated = JSON.parse(fs.readFileSync(fixturePath, 'utf8')) as RouteTable;
const writeBoundaryAssets = (bundle: string) => {
  const assets = path.join(bundle, ASSETS_RELATIVE_PATH);
  fs.mkdirSync(assets, { recursive: true });
  for (const name of REQUIRED_ARTIFACTS) fs.writeFileSync(path.join(assets, name.slice(1)), name);
};
const clone = <T>(value: T): T => JSON.parse(JSON.stringify(value)) as T;
const terminalRoute = (table: RouteTable): Route | undefined =>
  [...table.routes].reverse().find((route) => route.src === FALLBACK_PATTERN);

describe('EdgeOne deploy bundle routing', () => {
  it('keeps the pinned CLI fixture honest: compiled filesystem pattern, embedded conf, and the 200 fallback it corrects', () => {
    expect(generated.version).toBe(3);
    const handlers = generated.routes.filter((route) => route.handle === 'filesystem');
    expect(handlers).toHaveLength(1);
    expect(typeof handlers[0].src).toBe('string');
    expect(handlers[0].src).toContain('404|maintenance');
    const conf = generated.conf as { headers: { source: string }[]; rewrites: unknown[] };
    expect(conf.headers.map((rule) => rule.source)).toEqual([
      '/',
      '/index.html',
      '/oauth/consent',
      '/oauth-consent-bridge.html',
    ]);
    expect(conf.rewrites).toContainEqual({
      source: '/oauth/consent',
      destination: '/oauth-consent-bridge.html',
    });
    // The CLI's fallback already targets the 404 document here, but without a status it answers 200,
    // and an SPA-classified deployment would answer the shell; both are what the correction fixes.
    expect(terminalRoute(generated)).toEqual({
      src: FALLBACK_PATTERN,
      dest: NOT_FOUND_DOCUMENT,
      'server-name': 'file',
    });
  });

  it('corrects only the terminal fallback and preserves everything the CLI generated', () => {
    const result = correctRouteTable(generated);
    expect(result.corrected).toBe(true);
    expect(result.previous).toEqual({ dest: NOT_FOUND_DOCUMENT, status: undefined });
    expect(terminalRoute(result.table)).toEqual({
      src: FALLBACK_PATTERN,
      dest: NOT_FOUND_DOCUMENT,
      status: 404,
      'server-name': 'file',
    });
    // Every other entry and the embedded configuration are byte-identical to the CLI output.
    expect(result.table.routes.slice(0, result.index)).toEqual(
      generated.routes.slice(0, result.index),
    );
    expect(result.table.conf).toEqual(generated.conf);
    expect(correctRouteTable(result.table).corrected).toBe(false);
  });

  it('refuses a deployment classified as a single page application instead of accepting the shell fallback', () => {
    const spa = clone(generated);
    const index = spa.routes.findIndex((route) => route.src === FALLBACK_PATTERN);
    spa.routes[index] = { ...spa.routes[index], dest: '/index.html' };
    expect(() => verifyRouteTable(spa)).toThrow(/application shell/u);
    const corrected = correctRouteTable(spa);
    expect(terminalRoute(corrected.table)?.dest).toBe(NOT_FOUND_DOCUMENT);
    expect(terminalRoute(corrected.table)?.status).toBe(404);
    expect(() => verifyRouteTable(corrected.table)).not.toThrow();
  });

  it.each([
    ['the embedded conf block', (table: RouteTable) => delete table.conf],
    [
      'the filesystem handler',
      (table: RouteTable) => (table.routes = table.routes.filter((r) => r.handle !== 'filesystem')),
    ],
    ['the compiled pattern', (table: RouteTable) => (table.routes[0] = { handle: 'filesystem' })],
    [
      'a terminal fallback',
      (table: RouteTable) =>
        (table.routes = table.routes.filter((r) => r.src !== FALLBACK_PATTERN)),
    ],
  ])('fails closed when the generated table loses %s', (_label, mutate) => {
    const table = clone(generated);
    (mutate as (value: RouteTable) => void)(table);
    // Either stage may reject it — the correction refuses to run without a fallback entry, and the
    // verification refuses a table that would not answer a real 404. Both must fail closed.
    expect(() => verifyRouteTable(correctRouteTable(table).table)).toThrow(
      /Expected exactly one terminal catch-all route|EdgeOne routing verification failed/u,
    );
  });

  it('checks that the compiled pattern really covers the boundary documents', () => {
    const { table } = correctRouteTable(generated);
    expect(verifyRouteTable(table)).toMatchObject({ routes: 2, headers: 4, rewrites: 1 });
    expect(() =>
      verifyRouteTable(table, { requiredPaths: ['/definitely-not-an-asset.txt'] }),
    ).toThrow(/does not cover/u);
  });

  it('corrects a bundle once, then verifies it without further writes', () => {
    const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'edgeone-bundle-'));
    try {
      const routesPath = path.join(temporary, ROUTES_RELATIVE_PATH);
      writeBoundaryAssets(temporary);
      fs.mkdirSync(path.dirname(routesPath), { recursive: true });
      fs.writeFileSync(routesPath, JSON.stringify(generated, null, 2));
      expect(() => prepareBundle({ bundleDir: temporary, check: true })).toThrow(
        /status is undefined/u,
      );

      expect(prepareBundle({ bundleDir: temporary })).toMatchObject({
        changed: true,
        checked: false,
      });
      const written = readRouteTable(routesPath);
      expect(terminalRoute(written)).toMatchObject({ dest: NOT_FOUND_DOCUMENT, status: 404 });
      expect(written.conf).toEqual(generated.conf);
      expect(prepareBundle({ bundleDir: temporary })).toMatchObject({ changed: false });
      expect(prepareBundle({ bundleDir: temporary, check: true })).toMatchObject({ checked: true });
    } finally {
      fs.rmSync(temporary, { recursive: true, force: true });
    }
  });

  it('stages the complete bundle layout the pinned CLI expects', () => {
    const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'edgeone-stage-'));
    try {
      const dist = path.join(temporary, 'dist');
      const bundle = path.join(temporary, 'bundle');
      fs.mkdirSync(dist, { recursive: true });
      fs.mkdirSync(path.join(dist, 'assets'), { recursive: true });
      fs.writeFileSync(
        path.join(dist, '404.html'),
        fs.readFileSync(path.join(publicRoot, '404.html')),
      );
      fs.writeFileSync(
        path.join(dist, 'robots.txt'),
        fs.readFileSync(path.join(publicRoot, 'robots.txt')),
      );
      fs.writeFileSync(
        path.join(dist, 'index.html'),
        '<!doctype html><html><body>shell</body></html>\n',
      );
      fs.copyFileSync(
        path.join(publicRoot, 'oauth-consent-bridge.html'),
        path.join(dist, 'oauth-consent-bridge.html'),
      );
      fs.writeFileSync(path.join(dist, 'assets', 'app.js'), 'console.log("asset")\n');
      // A previously generated bundle must never be copied into its own assets directory.
      fs.mkdirSync(path.join(dist, '.edgeone'), { recursive: true });
      fs.writeFileSync(path.join(dist, '.edgeone', 'stale.json'), '{}\n');

      const { assets, staged } = stageBundle({
        distDir: dist,
        bundleDir: bundle,
        configPath: path.join(publicRoot, 'edgeone.json'),
      });
      expect(staged).toBeGreaterThan(0);
      const stagedNames = fs.readdirSync(assets).sort();
      expect(stagedNames).toEqual([
        '404.html',
        'assets',
        'index.html',
        'oauth-consent-bridge.html',
        'robots.txt',
      ]);
      expect(fs.existsSync(path.join(bundle, HOSTING_CONFIG_NAME))).toBe(true);
      expect(
        fs.readFileSync(path.join(assets, ASSETS_RELATIVE_PATH.split('/')[1], 'app.js'), 'utf8'),
      ).toContain('asset');

      // Staging refuses a dist that is missing a boundary document.
      fs.rmSync(path.join(dist, 'robots.txt'));
      expect(() =>
        stageBundle({
          distDir: dist,
          bundleDir: bundle,
          configPath: path.join(publicRoot, 'edgeone.json'),
        }),
      ).toThrow(/robots\.txt is missing/u);
    } finally {
      fs.rmSync(temporary, { recursive: true, force: true });
    }
  });

  it.each([
    [
      'several catch-alls',
      (table: RouteTable) =>
        table.routes.push({ src: '/.*', dest: NOT_FOUND_DOCUMENT, 'server-name': 'file' }),
    ],
    [
      'a catch-all that is not terminal',
      (table: RouteTable) => table.routes.push({ src: '^/after$', dest: '/index.html' }),
    ],
    [
      'a catch-all served by a function',
      (table: RouteTable) => {
        const index = table.routes.findIndex((route) => route.src === FALLBACK_PATTERN);
        table.routes[index] = { ...table.routes[index], 'server-name': 'ssr-node' };
      },
    ],
    [
      'a catch-all with an unknown target',
      (table: RouteTable) => {
        const index = table.routes.findIndex((route) => route.src === FALLBACK_PATTERN);
        table.routes[index] = { ...table.routes[index], dest: '/somewhere-else' };
      },
    ],
  ])('refuses to correct %s', (_label, mutate) => {
    const table = clone(generated);
    (mutate as (value: RouteTable) => void)(table);
    expect(() => correctRouteTable(table)).toThrow(/catch-all/u);
  });

  it('regenerates the trunk when a second build renames hashed assets, and rejects a stale table', () => {
    const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'edgeone-stale-'));
    const table = (compiled: string) =>
      JSON.stringify({
        version: 3,
        routes: [
          { handle: 'filesystem', src: compiled },
          { src: FALLBACK_PATTERN, dest: NOT_FOUND_DOCUMENT, status: 404, 'server-name': 'file' },
        ],
        conf: { headers: [{ source: '/', headers: [] }], redirects: [], rewrites: [], caches: [] },
      });
    try {
      const dist = path.join(temporary, 'dist');
      const bundle = path.join(temporary, 'bundle');
      const configPath = path.join(publicRoot, 'edgeone.json');
      const routesPath = path.join(bundle, ROUTES_RELATIVE_PATH);
      fs.mkdirSync(path.join(dist, 'assets'), { recursive: true });
      for (const name of ['404.html', 'robots.txt', 'oauth-consent-bridge.html'])
        fs.copyFileSync(path.join(publicRoot, name), path.join(dist, name));
      fs.writeFileSync(path.join(dist, 'index.html'), '<!doctype html><html></html>\n');
      fs.writeFileSync(path.join(dist, 'assets', 'app.aaaa1111.js'), 'old\n');
      fs.writeFileSync(path.join(dist, 'assets', 'delete-me.html'), 'old\n');

      // First build: a table that covers build one's assets verifies.
      stageBundle({ distDir: dist, bundleDir: bundle, configPath });
      fs.writeFileSync(
        routesPath,
        table(
          '^/assets/(app\\.aaaa1111\\.js|delete-me\\.html)$|^/(404|index|oauth-consent-bridge)\\.html$|^/robots\\.txt$',
        ),
      );
      expect(prepareBundle({ bundleDir: bundle, check: true })).toMatchObject({ checked: true });

      // Second build renames one hashed asset and drops another. Staging must invalidate the derived
      // routing so the pinned CLI regenerates it for this build's files.
      fs.writeFileSync(path.join(dist, 'assets', 'app.bbbb2222.js'), 'new\n');
      fs.rmSync(path.join(dist, 'assets', 'app.aaaa1111.js'));
      fs.rmSync(path.join(dist, 'assets', 'delete-me.html'));
      stageBundle({ distDir: dist, bundleDir: bundle, configPath });
      expect(fs.existsSync(routesPath)).toBe(false);

      // If a stale table ever survived, verification must refuse it: the renamed file is not covered.
      fs.writeFileSync(
        routesPath,
        table(
          '^/assets/(app\\.aaaa1111\\.js|delete-me\\.html)$|^/(404|index|oauth-consent-bridge)\\.html$|^/robots\\.txt$',
        ),
      );
      expect(() => prepareBundle({ bundleDir: bundle, check: true })).toThrow(/app\.bbbb2222\.js/u);

      // A table generated for the current build is accepted, and the correction then applies to it.
      const current = JSON.parse(
        table(
          '^/assets/app\\.bbbb2222\\.js$|^/(404|index|oauth-consent-bridge)\\.html$|^/robots\\.txt$',
        ),
      ) as {
        routes: { status?: number }[];
      };
      delete current.routes[1].status;
      fs.writeFileSync(routesPath, JSON.stringify(current));
      expect(prepareBundle({ bundleDir: bundle })).toMatchObject({ changed: true });
      expect(prepareBundle({ bundleDir: bundle, check: true })).toMatchObject({ checked: true });
    } finally {
      fs.rmSync(temporary, { recursive: true, force: true });
    }
  });

  it('refuses overlapping or symlinked staging targets', () => {
    const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'edgeone-guard-'));
    try {
      const dist = path.join(temporary, 'dist');
      fs.mkdirSync(dist, { recursive: true });
      fs.writeFileSync(
        path.join(dist, '404.html'),
        fs.readFileSync(path.join(publicRoot, '404.html')),
      );
      fs.writeFileSync(
        path.join(dist, 'robots.txt'),
        fs.readFileSync(path.join(publicRoot, 'robots.txt')),
      );
      fs.writeFileSync(path.join(dist, 'index.html'), '<!doctype html><html></html>\n');
      fs.copyFileSync(
        path.join(publicRoot, 'oauth-consent-bridge.html'),
        path.join(dist, 'oauth-consent-bridge.html'),
      );
      const configPath = path.join(publicRoot, 'edgeone.json');
      expect(() =>
        stageBundle({ distDir: dist, bundleDir: path.join(dist, 'bundle'), configPath }),
      ).toThrow(/must not contain one another/u);
      const linkTarget = path.join(temporary, 'elsewhere');
      fs.mkdirSync(linkTarget, { recursive: true });
      const bundle = path.join(temporary, 'bundle');
      fs.mkdirSync(path.join(bundle, '.edgeone'), { recursive: true });
      fs.symlinkSync(linkTarget, path.join(bundle, ASSETS_RELATIVE_PATH));
      expect(() => stageBundle({ distDir: dist, bundleDir: bundle, configPath })).toThrow(
        /symlinked path/u,
      );
    } finally {
      fs.rmSync(temporary, { recursive: true, force: true });
    }
  });

  it.each(['bundle', '.edgeone'])(
    'rejects a symlinked %s before deleting external routing',
    (component) => {
      const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'edgeone-parent-guard-'));
      try {
        const dist = path.join(temporary, 'dist');
        const bundle = path.join(temporary, 'bundle');
        const external = path.join(temporary, 'external');
        fs.mkdirSync(dist);
        for (const name of ['404.html', 'index.html', 'robots.txt', 'oauth-consent-bridge.html'])
          fs.writeFileSync(path.join(dist, name), name);
        const externalRoutes =
          component === 'bundle'
            ? path.join(external, '.edgeone', 'routes.json')
            : path.join(external, 'routes.json');
        fs.mkdirSync(path.dirname(externalRoutes), { recursive: true });
        fs.writeFileSync(externalRoutes, 'must remain unchanged');
        if (component === 'bundle') fs.symlinkSync(external, bundle, 'junction');
        else {
          fs.mkdirSync(bundle);
          fs.symlinkSync(external, path.join(bundle, '.edgeone'), 'junction');
        }
        expect(() =>
          stageBundle({
            distDir: dist,
            bundleDir: bundle,
            configPath: path.join(publicRoot, 'edgeone.json'),
          }),
        ).toThrow(/symlinked path/u);
        expect(fs.readFileSync(externalRoutes, 'utf8')).toBe('must remain unchanged');
      } finally {
        fs.rmSync(temporary, { recursive: true, force: true });
      }
    },
  );

  it('checks assets beyond the former file-count and directory-depth cutoffs', () => {
    const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'edgeone-full-inventory-'));
    try {
      writeBoundaryAssets(temporary);
      const assets = path.join(temporary, ASSETS_RELATIVE_PATH);
      fs.mkdirSync(path.join(assets, 'a', 'b', 'c', 'd'), { recursive: true });
      for (let i = 0; i < 405; i++) fs.writeFileSync(path.join(assets, `asset-${i}.js`), 'asset');
      fs.writeFileSync(path.join(assets, 'a', 'b', 'c', 'd', 'new-hash.js'), 'new asset');
      const corrected = correctRouteTable(generated).table;
      corrected.routes[0].src =
        '^/(404|index|oauth-consent-bridge)\\.html$|^/robots\\.txt$|^/asset-[0-9]+\\.js$';
      fs.writeFileSync(path.join(temporary, ROUTES_RELATIVE_PATH), JSON.stringify(corrected));
      expect(() => prepareBundle({ bundleDir: temporary, check: true })).toThrow(/new-hash\.js/u);
      fs.rmSync(path.join(assets, 'a'), { recursive: true });
      fs.writeFileSync(path.join(assets, 'zz-new-hash.js'), 'new asset');
      expect(() => prepareBundle({ bundleDir: temporary, check: true })).toThrow(
        /zz-new-hash\.js/u,
      );
    } finally {
      fs.rmSync(temporary, { recursive: true, force: true });
    }
  });

  it.each(REQUIRED_ARTIFACTS)('rejects a bundle missing the actual %s file', (artifact) => {
    const temporary = fs.mkdtempSync(path.join(os.tmpdir(), 'edgeone-missing-document-'));
    try {
      writeBoundaryAssets(temporary);
      fs.writeFileSync(
        path.join(temporary, ROUTES_RELATIVE_PATH),
        JSON.stringify(correctRouteTable(generated).table),
      );
      fs.rmSync(path.join(temporary, ASSETS_RELATIVE_PATH, artifact.slice(1)));
      expect(() => prepareBundle({ bundleDir: temporary, check: true })).toThrow(
        /missing a regular boundary document/u,
      );
    } finally {
      fs.rmSync(temporary, { recursive: true, force: true });
    }
  });

  const prepared = path.resolve(root, 'dist-edgeone', ROUTES_RELATIVE_PATH);
  const describePrepared = fs.existsSync(prepared) ? describe : describe.skip;
  describePrepared('prepared bundle in this checkout', () => {
    it('holds a verified table with the corrected terminal fallback', () => {
      expect(
        prepareBundle({ bundleDir: path.resolve(root, 'dist-edgeone'), check: true }),
      ).toMatchObject({
        checked: true,
      });
    });
  });
});
